"""
מחולל דוחות HTML אינטראקטיביים
"""

from jinja2 import Template
import datetime


class ReportGenerator:
    """יוצר דוח HTML מקיף"""
    
    def __init__(self, analyzer, visualizer, stats_analyzer):
        """
        Args:
            analyzer: GrowthCurveAnalyzer
            visualizer: Visualizer
            stats_analyzer: StatisticalAnalyzer
        """
        self.analyzer = analyzer
        self.visualizer = visualizer
        self.stats = stats_analyzer
    
    def generate_html_report(self, output_path='report.html', title='Growth Curve Analysis Report'):
        """
        יוצר דוח HTML מלא
        
        Args:
            output_path: נתיב לשמירת הדוח
            title: כותרת הדוח
        """
        # יצירת כל הגרפים
        growth_curves_fig = self.visualizer.plot_growth_curves()
        growth_rate_fig = self.visualizer.plot_growth_rate_comparison()
        heatmap_fig = self.visualizer.plot_parameter_heatmap()
        
        # המרה ל-HTML
        growth_curves_html = growth_curves_fig.to_html(full_html=False, include_plotlyjs='cdn')
        growth_rate_html = growth_rate_fig.to_html(full_html=False, include_plotlyjs=False)
        heatmap_html = heatmap_fig.to_html(full_html=False, include_plotlyjs=False)
        
        # טבלאות
        results_html = self.analyzer.results.to_html(index=False, classes='table table-striped')
        summary_html = self.stats.generate_summary_table().to_html(classes='table table-bordered')
        
        # Template
        html_template = """
<!DOCTYPE html>
<html lang="he" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 20px;
        }
        .container {
            background: white;
            border-radius: 15px;
            padding: 30px;
            margin-top: 20px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.1);
        }
        h1 {
            color: #667eea;
            text-align: center;
            margin-bottom: 30px;
            font-weight: bold;
        }
        h2 {
            color: #764ba2;
            border-bottom: 3px solid #667eea;
            padding-bottom: 10px;
            margin-top: 40px;
            margin-bottom: 20px;
        }
        .plot-container {
            margin: 30px 0;
            padding: 20px;
            background: #f8f9fa;
            border-radius: 10px;
        }
        .table {
            font-size: 14px;
        }
        .table-striped tbody tr:nth-of-type(odd) {
            background-color: rgba(102, 126, 234, 0.05);
        }
        .metadata {
            background: #e9ecef;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 30px;
        }
        .badge {
            font-size: 14px;
            padding: 8px 15px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🧬 {{ title }}</h1>
        
        <div class="metadata">
            <p><strong>📅 תאריך יצירה:</strong> {{ date }}</p>
            <p><strong>🔬 מספר דגימות:</strong> <span class="badge bg-primary">{{ n_samples }}</span></p>
            <p><strong>📊 מודל:</strong> <span class="badge bg-success">{{ model }}</span></p>
        </div>
        
        <h2>📈 Growth Curves</h2>
        <div class="plot-container">
            {{ growth_curves_plot | safe }}
        </div>
        
        <h2>⚡ Growth Rate Comparison</h2>
        <div class="plot-container">
            {{ growth_rate_plot | safe }}
        </div>
        
        <h2>🔥 Parameters Heatmap</h2>
        <div class="plot-container">
            {{ heatmap_plot | safe }}
        </div>
        
        <h2>📋 Results Table</h2>
        <div class="table-responsive">
            {{ results_table | safe }}
        </div>
        
        <h2>📊 Statistical Summary</h2>
        <div class="table-responsive">
            {{ summary_table | safe }}
        </div>
        
        <hr style="margin-top: 50px;">
        <footer class="text-center text-muted">
            <p>Generated by <strong>BioData Studio</strong> 🧬</p>
            <p>Advanced Growth Curve Analysis Platform</p>
        </footer>
    </div>
</body>
</html>
        """
        
        template = Template(html_template)
        
        # מילוי ה-template
        html_content = template.render(
            title=title,
            date=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            n_samples=len(self.analyzer.results),
            model=self.analyzer.results['Model'].iloc[0] if 'Model' in self.analyzer.results.columns else 'N/A',
            growth_curves_plot=growth_curves_html,
            growth_rate_plot=growth_rate_html,
            heatmap_plot=heatmap_html,
            results_table=results_html,
            summary_table=summary_html
        )
        
        # שמירה לקובץ
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        print(f"✅ דוח נשמר בהצלחה ב: {output_path}")
        return output_path
